name: faustina
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  uuid: ^4.3.0 
  crypto: ^3.0.7
  path: ^1.8.3
  pdf: ^3.10.4
  printing: ^5.10.2
  intl: ^0.18.1
  syncfusion_flutter_datepicker: ^23.1.43
  fl_chart: ^0.66.2
  permission_handler: ^11.0.1
  google_sign_in: ^6.1.5
  csv: ^5.0.2
  http: ^1.1.0
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.7.1  
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/icon/icon.png
    - assets/icon/splash.png

flutter_native_splash:
  color: "#7C3E45"
  image: assets/icon/splash.png
  android: true
  ios: true
  web: false


flutter_launcher_icons:
  android: true
  ios: true
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#FFFFFF"